# Generated by Django 3.2.25 on 2024-05-27 09:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240519_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.course_image_file_path),
        ),
    ]
